services:
  db:
    container_name: 'coffeeDB'
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
  test-db:
    container_name: 'TestCoffeeDB'
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pass123
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
